# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iaNheq1z7C_Qp1RfqapYnmkfGag_ghr2
"""

x = 5
j = "Jhon"
print(type(x))
print(type(j))

x, y, z = "Appale", "Orange", "Mango"
print(x)
print(y)
print(z)

x = y = z = "Appale"
print(x)
print(y)
print(z)

fruits = ["Appale", "Orange", "Mango"]
x = y = z = fruits
print(x)
print(y)
print(z)

list1 = ["Mustafa", 33, True, 2.3, 'B']
print(len(list1))
list1[-5:0]

list1[1::3]

list1[::-1] #reverse the list

fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2

print(mytuple)

car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.keys()

print(x) #before the change

car["color"] = "white"

print(x) #after the change

listone = ["Mustafa", 33, True, 2.3, "Banana", "Raza"]
listtwo = []
for i in listone:
  if type(i) == str:
    listtwo.append(len(i))

listtwo

i = 1
while i<6:
  print(i)
  i+=1

