# -*- coding: utf-8 -*-
"""Lab-01 ungraded Task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TE-A8ixdwrcvzJC4gAqTLwdPqzmYgAT2

# LIST


create a list [1, 2, 3, 4, 5] named as my_list.

Add an element "6" to the end of the list.

Insert an element "7" at a specific index "2" (index, value).

Remove the first occurrence of a value "3".

Remove and return the last element.

Extract elements from index 1 to 3 (inclusive).
"""

List1 = [1, 2, 3, 4, 5]
List1.append(6)

List1.insert(2,7)
List1

List1.remove(3)

List1.pop()

List1[1:4]

"""# SET
create two sets set1 with values {1, 2, 3, 6, 7} and set2 with values {3, 4, 5, 6}.

Also find (((set1 difference set2) union set2) Intersection set1) and store result in set3
"""

set1 = {1, 2, 3, 6, 7}
set2 = {3, 4, 5, 6}

diffset = set1.difference(set2)

uniset = diffset.union(set2)

set3 = uniset.intersection(set1)

"""# **FUNCTIONS**

Find the maximum length word in a list of words using the max function and a lambda key function.
"""

namelist = ["Mustafa", "Zayan", "Huzaifa", "Raza"]
maxlenword = max(namelist, key=lambda word: len(word))
print("The longest word is:", maxlenword)

"""# **LIST COMPREHENSION**

Using List Comprehension concept calculate the length of each word in a list of words.

words = ["apple", "banana", "cherry"]

output_list = [5, 6, 6]
"""

words = ["apple", "banana", "cherry"]
output_list = [len(word) for word in words]
print(output_list)

"""# FILING
Resolve the error using try, catch Block

```
with open("myfile.txt") as f:
    for line in f:
        print(line)
```

create a file myfile.txt and dumps set3 and final list in myfile.txt using json library
"""

import json

try:
    with open("myfile.txt") as f:
        for line in f:
            print(line)
except FileNotFoundError:
    print("File not found")

set3 = {"apple", "banana", "cherry"}
final_list = [5, 6, 6]

with open("myfile.txt", "w") as f:
    json.dump({"set3": list(set3), "final_list": final_list}, f)

print("Data dumped into myfile.txt successfully.")